version: '3'
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - 3020:8080
    volumes:
      - ./schema/schema.yml:/usr/share/nginx/html/schema.yml
    environment:
      API_URL: ./schema.yml
