// THIS FILE IS GENERATED BY CODE GENERATOR. DO NOT CHANGE MANUALLY.
/* tslint:disable */
/* eslint-disable */
import Pet from "./models/Pet";
import Error from "./models/Error";

export interface listPetsRequest {
  limit?: number;
  offset?: number;
}

export interface listPetsResponse {
  pets: Pet[];
}

export interface listPetsPathParameter {}

export interface createPetsRequest {
  name: string;
  category: 1 | 2 | 3;
  sex: "male" | "female";
}

export interface createPetsResponse {
  pet: Pet;
}

export interface createPetsPathParameter {}

export interface createPets422Error {
  reason: string;
}

export interface showPetByIdRequest {}

export interface showPetByIdResponse {
  pet: Pet;
}

export interface showPetByIdPathParameter {
  petId: string;
}
